export const GAME_CONFIG = {
  fixedStepSeconds: 1 / 60,
  lockstepMaxSteps: 4,
  gravity: -24,
  gameplayZ: 0,
  zLockEpsilon: 0.001,
  player: {
    radius: 0.42,
    height: 1.8,
    maxHealth: 3,
    moveSpeed: 6.5,
    groundAcceleration: 38,
    groundDeceleration: 44,
    airAcceleration: 18,
    jumpSpeed: 10.5,
    coyoteSeconds: 0.1,
    jumpBufferSeconds: 0.12,
    doubleJumpEnabled: false,
    invulnerabilitySeconds: 1.25,
    respawnProtectionSeconds: 1,
  },
  camera: {
    verticalSize: 10,
    deadZoneWidth: 3.5,
    deadZoneHeight: 2,
    damping: 9,
  },
  fallThresholdY: -8,
} as const;
