import type { TranslationDictionary } from "./strings";

export const ar: TranslationDictionary = {
  menuPlay: "ابدأ اللعب",
  menuSettings: "الإعدادات",
  menuQuit: "خروج",
  hudScore: "النقاط",
  hudCollectibles: "المقتنيات",
  hudHealth: "الصحة",
  tutorialMove: "تحرك",
  tutorialJump: "اقفز",
  tutorialPause: "إيقاف مؤقت",
  errorLoadLevel: "تعذر تحميل المرحلة",
  errorSaveData: "تعذر حفظ البيانات",
  victoryTitle: "أحسنت!",
  victoryContinue: "متابعة",
  gameOverTitle: "انتهت اللعبة",
  gameOverRetry: "أعد المحاولة",
  audioTitle: "الصوت",
  audioMusic: "الموسيقى",
  audioSfx: "المؤثرات الصوتية",
  audioMute: "كتم الصوت",
  clearData: "مسح البيانات",
  clearDataConfirm: "هل تريد مسح كل البيانات؟",
  controlLeft: "يسار",
  controlRight: "يمين",
  controlJump: "قفز",
  controlAttack: "هجوم",
  controlPause: "إيقاف مؤقت",
};
