import type { TranslationDictionary } from "./strings";

export const ar: TranslationDictionary = {
  gameTitle: "ورشة الغروب",
  startGame: "ابدأ اللعب",
  resume: "متابعة",
  restartLevel: "إعادة المستوى",
  returnToMenu: "القائمة الرئيسية",
  victoryMessage: "أحسنت! وصلت إلى البوابة",
  gameOverMessage: "انتهت المحاولة",
  clearSavedData: "مسح البيانات المحفوظة",
  pause: "إيقاف مؤقت",
  menuPlay: "ابدأ اللعب",
  menuSettings: "الإعدادات",
  menuQuit: "خروج",
  hudScore: "النقاط",
  hudCollectibles: "المقتنيات",
  hudHealth: "الصحة",
  tutorialMove: "تحرك",
  tutorialJump: "اقفز",
  tutorialPause: "إيقاف مؤقت",
  errorLoadLevel: "تعذر تحميل المرحلة",
  errorSaveData: "تعذر حفظ البيانات",
  victoryTitle: "أحسنت! وصلت إلى البوابة",
  victoryContinue: "متابعة",
  gameOverTitle: "انتهت المحاولة",
  gameOverRetry: "أعد المحاولة",
  audioTitle: "الصوت",
  audioMusic: "الموسيقى",
  audioSfx: "المؤثرات الصوتية",
  audioMute: "كتم الصوت",
  clearData: "مسح البيانات المحفوظة",
  clearDataConfirm: "هل تريد مسح كل البيانات؟",
  controlLeft: "يسار",
  controlRight: "يمين",
  controlJump: "قفز",
  controlAttack: "هجوم",
  controlPause: "إيقاف مؤقت",
};
