import type { TranslationDictionary } from "./strings";

export const en: TranslationDictionary = {
  gameTitle: "Sunset Workshop",
  startGame: "Start Game",
  resume: "Resume",
  restartLevel: "Restart Level",
  returnToMenu: "Main Menu",
  victoryMessage: "Well done! You reached the gate",
  gameOverMessage: "Attempt over",
  clearSavedData: "Clear Saved Data",
  pause: "Pause",
  loadingLevel: "Loading level…",
  menuPlay: "Play",
  menuSettings: "Settings",
  menuQuit: "Quit",
  hudScore: "Score",
  hudCollectibles: "Collectibles",
  hudHealth: "Health",
  hudCheckpoint: "Progress saved",
  tutorialMove: "Use the movement controls to cross the Sunset Workshop safely and reach the gate.",
  tutorialJump: "Jump",
  tutorialPause: "Pause",
  errorLoadLevel: "Unable to load level",
  errorSaveData: "Unable to save data",
  victoryTitle: "Victory!",
  victoryContinue: "Continue",
  gameOverTitle: "Game Over",
  gameOverRetry: "Try Again",
  audioTitle: "Audio",
  audioMusic: "Music",
  audioSfx: "Sound Effects",
  audioMute: "Mute",
  clearData: "Clear Data",
  clearDataConfirm: "Clear all saved data?",
  confirmClearData: "Confirm Clear",
  cancelClearData: "Cancel",
  controlLeft: "Left",
  controlRight: "Right",
  controlJump: "Jump",
  controlAttack: "Attack",
  controlPause: "Pause",
};
